######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 21 13:29:54 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    mainwin.cpp

FORMS += \
    mainwin.ui

HEADERS += \
    mainwin.h \
    mlabel.h \
    textures.h
